DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `usp_testingResetCustomer3Data`()
BEGIN

-- disable foreign key constraints first
	set foreign_key_checks=0;
    set sql_safe_updates=0;
    
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (401, 'Antalocy, S.', 'P.O. Box 336', 'Seattle', 'WA', '98155          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (402, 'Nair, Phalo', '214 Angela Ave', 'Jersey City', 'NJ', '07304          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (403, 'Roush, M', '5111 Ambergate L', 'Chapi', 'SC', '29036          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (404, 'Williams, Bobby', '9001 Southbay Drive', 'Bronx', 'NY', '10467          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (405, 'Burnett, Muralikrishna', '60 Coppermine Road', 'Naperville', 'IL', '60540          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (406, 'Agarwala, Troy', '2308 Fair St.', 'Wapakoneta', 'OH', '45895          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (407, 'Torr, James', '465 Buckland Hills Dr. Apt 311', 'Dubli', 'NY', '90210          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (408, 'Anderson, Ala', '15650A Vineyard Blvd  143', 'Albuquerque', 'NM', '87101          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (409, 'Lowery, Shane', '1127 Herbert J.', 'Philadelphia', 'PA', '19153          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (410, 'Syed, Mike', '2501 Mcgee', 'Horn Lake', 'MS', '38637          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (411, 'Harrison, Jeff', '2560 W. Shaw L', 'Dallas', 'TX', '75201          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (412, 'Dunlavy, Kare', '1707 4Th Ave Se', 'Anytow', 'CO', '80204          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (413, 'Fgsgsg, Senthil', '2025 E Campbell   #143', 'Indianapolis', 'I', '46228-3356     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (414, 'Vang, Karl', '327 Franklin Street', 'Edina', 'M', '55435          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (415, 'Green, Etha', '810 First Street Ne', 'Oakland', 'CA', '94612          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (416, 'Elseman, Felix', '12 E.31St St. Ste 1205', 'W. Covina', 'CA', '91719          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (417, 'Blackman, Armando', '6333 Mount Ada Rd', 'Alpharetta', 'GA', '30004          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (418, 'Page, Patrick', '505 Main St', 'Williamsville', 'NY', '14221-4520     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (419, 'Vidal, William', '43 Kraft L', 'Springfield', 'MA', '01111-0001     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (420, 'Schulte, Romi', '147 Afton Ave.', 'Chica', 'IL', '60626          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (421, 'Allen, Craig', 'P.O. Box 50016', 'Pullma', 'WA', '99164          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (422, 'Sowell, Janet', '189 Commcerce Court', 'Baltimore', 'MD', '21201          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (423, 'Rennells, Ram', '310 N. Willomet Ave.', 'Metairie', 'LA', '70002          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (424, 'Rao, Christina', '518 Elmwood Terrace', 'Avenel', 'NJ', '07001          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (425, 'Phinney, Sue', '624 Aiello St', 'Comstock Park', 'MI', '49321-9344     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (426, 'Young, Jacquely', '11550 Florida Blvd', 'Richmond', 'VA', '23227          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (427, 'Wade, Jp', '6118 Carnation Road', 'Tallahassee', 'FL', '32305          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (428, 'Plasha, Joe', '812 West 13Th Street', 'Akro', 'OH', '44113          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (429, 'Perez, Terrence', '2325 West Pensacola Street', 'Farmington Hills', 'MI', '48335          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (430, 'Moore, Richard', '78 Mckown Road', 'Cedar Rapids', 'IA', '52401          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (431, 'Laforest, Do', 'Plntatio', 'Atlanta', 'GA', '30324          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (432, 'Ayyappan, Andrew', '1671 Hampton Knoll Drive', 'Markham', 'IL', '60426          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (433, 'Arrington, Mallikarjuna', '2551 Wideworld', 'Miami', 'FL', '33173          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (434, 'Oriol, Cecilia', '1108 Fleming Ct.   103', 'Chandler', 'AZ', '85225          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (435, 'Garrison, Joel', '16951, Addison Rd', 'New City', 'NY', '10956-6815     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (436, 'Cloud, Kevi', '652 N Sam Housto', 'Jackso', 'MI', '49202          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (437, 'Little, Walto', '10566 Tiger Point', 'Downingtow', 'PA', '19335          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (438, 'Moore, Mv', '6315 N 16Th St, 229', 'Brookly', 'NY', '11219          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (439, 'Clark, Donald', '1015 E. 20Th St Apt C', 'Plano', 'TX', '75086          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (440, 'Vatcheva, Scott', '315 Court Street', 'Marshall', 'WI', '53559          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (441, 'Owen, Mark', 'P.O. Box 1537', 'Belleville', 'NJ', '07109          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (442, 'Meeker, Tsao-shiang', '2100 Paul Edwin Terr', 'Olathe', 'KS', '66062          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (443, 'Xiong, J', 'Po Box 8403', 'Topeka', 'KS', '66604-1877     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (444, 'Truesdale, David', 'Po Box 6459', 'Huntsville', 'AL', '35805          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (445, 'Miller, Bassam', '10 Erick Rd #15', 'Hyattsville', 'MD', '20783          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (446, 'Stone, Milind', '44 Kinler', 'Saint Paul', 'M', '55116          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (447, 'Borskiy, Jamie', '12301 Warner Dr', 'St. Augustine', 'FL', '32084          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (448, 'Larson, Heriberto', '7623 Matera St #103', 'Alpine', 'AL', '35014          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (449, 'Chandrasekhar, Yagnaraju', '2149 West Dunlap Avenue', 'Bethalto', 'IL', '62010          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (450, 'Patthana, Patrick', '124 Austin Building', 'Peoria', 'IL', '61614          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (451, 'Balija, Jeff', '4723. W. Braddock Road', 'Dallas', 'TX', '75252          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (452, 'Butler, Paul', '125 Rosewood Drive', 'Florence', 'SC', '29501          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (453, 'Smith, Uma', '915 Sw Harriso', 'Kc', 'MO', '64151          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (454, 'Shakeel, Cynthia', '120 Blue Ridge Trace', 'Plainsboro', 'NJ', '08536          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (455, 'Faver, Michael', '260 Franklin Turnpike Apt 513', 'Lincol', 'NE', '68512          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (456, 'Ehardt, Faina', '4747 Mclane Parkway', 'Redwood City', 'CA', '94062          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (457, 'Hughes, Steve', '21555 Oxnard Street', 'Fento', 'MO', '63026          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (458, 'Mike, Bill', '88 Silva Lane', 'Berkeley', 'CA', '94720          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (459, 'Byker, Samuel', '2801 East College Way', 'Plano', 'TX', '75093          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (460, 'Weathers, Sandhya', 'Its - City Hall - Room 6', 'Bowdo', 'GA', '30108          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (461, 'Bodnovich, Vivek', '1000 Lakeside Dr.', 'Atlanta', 'GA', '30339          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (462, 'Cofer, Kathy', '1441 Schilling Place', 'Burr Ridge', 'IL', '60527          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (463, 'Pickens, Bumpy', '729 Woodmere Creek Loop', 'Pittsburgh', 'PA', '15233          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (464, 'Bagent, Tom', '1120 N St.', 'Camp Hill', 'PA', '17011          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (465, 'Sui, Do', '6607 Brodis Lane  335', 'Parsippany', 'NJ', '07054          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (466, 'Howard, Harold', '920 Harvest Dr', 'Grand Prairie', 'TX', '75050          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (467, 'Myl, Caroly', '4343 Warm Springs Rd Apt 1019', 'Butler', 'PA', '16002          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (468, 'Ross, Kevi', '1955 Amber Trail Rd', 'Dayto', 'MD', '21036          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (469, 'Schmitt, Tom', '12001 Sw 14Th Street', 'Valley Forge', 'PA', '19482          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (470, 'Thompson, Elsy', '916 N. Lincol', 'Troy', 'MI', '48099          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (471, 'Stapleton, Victor', '267 Amboy Avenue', 'Muske', 'MI', '49441-4588     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (472, 'Tallada, Raghu', '128 Greenbriar Dr', 'Madison Heights', 'MI', '48976          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (473, 'Grant, Murali', '1344 B Street', 'Queens Village', 'NY', '11427          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (474, 'Key, David', '2 Pierce Place', 'Streamwood', 'IL', '60107          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (475, 'Gupta, Deborah', '5 Lilly Pond Circle', 'Southboro', 'MA', '01772          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (476, 'Sharma, Carlo', '18081 Midway Rd', 'Washingto', 'DC', '20011          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (477, 'Horton, James', '2455 Paces Ferry Rd.', 'Williamsville', 'NY', '14221          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (478, 'Millard, Dwayne', '634 Koehler Road', 'Seattle', 'WA', '98178          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (479, 'Kattekula, Luis', '14252 St Rt 65', 'Eden Prairie', 'M', '55346          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (480, 'Hanak, Shara', '1200 N. Market St.', 'St. Louis', 'MO', '63113          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (481, 'Young, Chris', '6705 Harlan Drive', 'Falls Church', 'VA', '22043          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (482, 'Rampel, Joh', '123-12 Gcp', 'Waco', 'TX', '76710          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (483, 'Kumar, Gary', '183 Loudon Rd, Apt   4', 'Columbus', 'OH', '43201          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (484, 'Gallaspy, Bill', '2794 Blarefield Driev', 'New York', 'NY', '10041          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (485, 'Kerr, Harper', 'Po Box 2337', 'St Albans', 'VT', '05478          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (486, 'Rose, Ala', 'P.O. Box 8553', 'St. Petersburg', 'FL', '33704          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (487, 'Pak, Robert', '101 Satinwood Drive', 'Mechanicsville', 'VA', '23111          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (488, 'Howland, Robert', '5806 Leanne L', 'Pittsburg', 'CA', '94565          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (489, 'Kauffmanm, Lashonda', '211 Main Street', 'Sarasota', 'FL', '34243          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (490, 'Johnson, Balasundaram', '850 Cherry', 'New York', 'NY', '10292          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (491, 'Grahovek, Stephe', '12 Booth Street', 'Germantow', 'T', '38138          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (492, 'Brown, Nagarju', 'Po Box 50', 'Poughkeepsie', 'NY', '12603          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (493, 'Stewart, Christopher', '1 Court Circle', 'Georgetow', 'TX', '78628          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (494, 'Barrios, Rajeev', '471 Regan L', 'Northborough', 'MA', '01532          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (495, 'Smith, Arthur', 'P.O. Box 190886', 'Laurelto', 'NY', '11413          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (496, 'Conlan, Armstrong', '3404 Tulane Drive Apt. 21', 'Forestville', 'MD', '20747          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (497, 'Mccord, Alex', '1731 Ne 141 St', 'Schaumburg', 'IL', '60173          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (498, 'Brasher, Ruth', '4 S. Highview Cir', 'Charlotte', 'NC', '28211          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (499, 'Mayo, Kevi', '2882 Tall Oaks Ct', 'Dayto', 'OH', '45449          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (500, 'Bivans, Paul', '17B Pauline Street', 'Columbus', 'GA', '31909          ');

INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (501, 'Korde, Shubha', '1326 Mississippi Street', 'San Jose', 'CA', '95134          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (502, 'Mauthe, Hipolito', '1262 11Th Avenue', 'Philadelphia', 'PA', '19128-4732     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (503, 'Woolf, Ginny', '16021 N 30Th St Unit 110', 'Housto', 'TX', '77060          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (504, 'Richards, Kim', '1800 Harrison St, 9Th Fl', 'Milford', 'CT', '06460          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (505, 'Larsen, Kristina', '3325 S Douglas Av', 'San Francisco', 'CA', '94122          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (506, 'Hacker, Rube', '3 Willow Way', 'Cleveland', 'OH', '44115          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (507, 'Seeley, Joe', '1101 Monterey Blvd', 'Secaucus', 'NJ', '07094          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (508, 'Dzialak, Francisco', '9523 Blake Lane 101', 'Mesquite', 'TX', '75181-1266     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (509, 'Cassara, Glen', '5514 W. Como Ave.', 'Va', 'WA', '98654          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (510, 'Bassett, Mark', '12750 Fair Lakes Circle', 'Farmingto', 'CT', '06032          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (511, 'Diggity, Shailesh', '7 Easton Oval', 'Parsippany', 'NJ', '07054          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (512, 'Armalie, Dennis', '50 East 21St Street', 'Salinas', 'CA', '93907          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (513, 'Miller, Billy', '1123A Kingbolt Circle Dr', 'Castro Valley', 'CA', '94552          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (514, 'Caldwell, Luminita', '170 Big Perry Rd', 'Midlothia', 'VA', '23114          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (515, 'Herrera, Ke', '8231 Princeton Sq Blvd', 'Bridgeto', 'MO', '63044-1785     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (516, 'Tucker, Do', '25 Abenaki Road', 'Charlotte', 'NC', '28211          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (517, 'Nair, Reggie', '4536 Castleton Rd', 'Glastonbury', 'CT', '06033          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (518, 'Yerrapu, Michele', '12892 Glendon Street', 'Falls Church', 'VA', '22043          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (519, 'Julien, Gil', '59 Clinton St', 'Countryside', 'IL', '60525-4088     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (520, 'Spencer, Robert', 'P.O. Box 38136', 'Newark', 'NJ', '07106          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (521, 'Giglio, Ric', '319 Krams Avenue', 'Pembroke Pines', 'FL', '33025          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (522, 'Wheatley, Paul', '295 Firstmerit Circle', 'Alle', 'TX', '75002          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (523, 'Bommareddy, Richard', '4415 Canoga Ave', 'New York', 'NY', '10016-6702     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (524, 'Vera, Kevi', '9379 '''''''' Street', 'Aurora', 'IL', '60504          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (525, 'Rozenberg, Angela', '1310, Oakcrest Dr.', 'Falls Church', 'VA', '22043          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (526, 'Agrawal, Weining', '1435 Chrome Hill Road', 'Chickasha', 'OK', '73018          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (527, 'Grottolo, Satya', '710 1/2 Stark St.', 'Manchester', 'CT', '06040          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (528, 'Malausky, Scott', '14000 Hwy 82W', 'Forest', 'VA', '24551          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (529, 'Erdman, Paul', '5021 Shinnecock Hills Dr. N.W.', 'Dallas', 'TX', '75218          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (530, 'Soucie, Kimberly', '6694 Cottontown Rd', 'Needham', 'MA', '02494          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (531, 'Lance, Al', 'Admn 122', 'Columbia', 'SC', '29223          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (532, 'Pat, Ed', '1601 Bryan St., Suite 27-037', 'Mclea', 'IL', '61754-7541     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (533, 'Brown, Ashwini', '821 S Williams', 'Cullma', 'AL', '35055          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (534, 'Krani, George', '2014 S 102Nd Street, 210 C', 'Maynard', 'MA', '01754          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (535, 'Routhu, Mark', '476 Viola Rd.', 'Frankli', 'T', '37067          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (536, 'Johnson, Wendy', '1223 Cannes Court', 'Mt Horeb', 'WI', '53572          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (537, 'Justme, David', '57 Cheshire Dr', 'Jackso', 'MI', '49202          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (538, 'Nevils, William', '1200 N. Market St.', 'Centerville', 'M', '55038          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (539, 'Mills, Richard', '8 Glenford Lane', 'Jacksonville,', 'FL', '32217-4313     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (540, 'Antosca, Andrew', '485 Duane Terrace', 'Ann Arbor', 'MI', '48108          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (541, 'Pao, Sidoneo', '200 Engamore Lane', 'Tallahassee', 'FL', '32315          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (542, 'Nolan, Joseph', '13 N San Marcos Rd', 'Camillus', 'NY', '13031          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (543, 'Otis, Connie', '165 Timmons Road', 'Columbus', 'I', '43231          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (544, 'Val, Zarina begum', '34-38 71St St', 'Plano', 'TX', '75024          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (545, 'Wright, Venkat', '800 Crescent Center Drive, Sui', 'Jamaica', 'NY', '11435          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (546, 'Mullen, Charles', '409 Eleventh St.', 'Parsippany', 'NJ', '07054          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (547, 'Kelly, George', '7852 Ponce Ave', 'Palatine', 'IL', '60074          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (548, 'Humble, Je', '430 Castle Dr', 'Woodland Hills', 'CA', '91364          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (549, 'Rogers, L', 'P. O.  Box  53167', 'St. Louis', 'MO', '63110          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (550, 'Rivera, Joseph', '12033 Foundation Place', 'Netcong', 'NJ', '07857          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (551, 'Nelsen, Jim', '4251 Parkalwn Ave, # 202', 'Ft Washingto', 'MD', '20744          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (552, 'Wilson, Kenneth', '1011 N 26Th', 'West Des Moines', 'IA', '50266          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (553, 'Jackson, Sukumar', '118 Kendrick St.', 'Tampa', 'FL', '33607          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (554, 'Pukala, James', '35 W59Th Street', 'Baltimore', 'MD', '21207          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (555, 'Wen, Wayne', '1950 Franklin Street', 'Vallejo', 'CA', '94590          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (556, 'Smth, Lana', '2567 South 156 Avenue', 'Warre', 'PA', '16365          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (557, 'Landin, Peggy', '3011 Woodloop L', 'Phoenix', 'AZ', '85022          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (558, 'Loest, Monica', '14 Locust Grove Road', 'Lenoir', 'NC', '28645          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (559, 'Oliveira, Puli', '3219 S Grace Ave', 'Jersey City', 'NJ', '07302          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (560, 'Bohra, Mark', 'Brgy. 68, San Francisco,', 'Succasunna', 'NJ', '07876          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (561, 'Varner, Sangil', '940 W 131St St', 'Legaspi City', 'PR', '04500          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (562, 'Reinhart, Terry', 'East Hall, Room 7', 'Toronto', 'T', '37415          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (563, 'Kidwell, Suresh', '4005 Brookhaven Club Drive', 'Housto', 'TX', '77269-2370     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (564, 'Hogen, Fausitna', '315 Bart Rd.', 'Leominster', 'MA', '01453          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (565, 'Tamunday, D', '1409,Roper Mountain Road, Apt', 'Hopatcong', 'NJ', '07843          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (566, 'Hunter, Deepa', '1951 Cypress Street', 'Columbia', 'SC', '29201          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (567, 'Fuglemsmo, Johnny', '3543 Simpson Ferry Rd', 'Taylor Mill', 'KY', '41015-4124     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (568, 'Schaa, Greg', '821 Azores Cir', 'Austi', 'TX', '78704          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (569, 'Oakes, Tyrone', '2383 Akers Mill Road', 'Columbus', 'OH', '43220          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (570, 'Bingham, Robert', '44 Boulder Avenue', 'Birmingham', 'AL', '35215          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (571, 'Paik, Bria', '2000 Westminster Lane', 'Rochester Hills', 'MI', '48307          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (572, 'Smith, Lloyd', '9432 Downing Circle', 'Pullma', 'WA', '99164          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (573, 'Torres, Peter', '1102 North 8Th Street', 'Westminster', 'CO', '80021          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (574, 'Hayes, Da', 'P.O. Box 777', 'Brookly', 'NY', '11235          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (575, 'Jackson, Laura', '3570- C, Meadowglenn Apts', 'Le Mars', 'IA', '51031          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (576, 'Shepherd, Jamie', '1341 East Thacker Street', 'Highlands Ranch', 'CO', '80126          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (577, 'Pluff, Mark', '9420 Key West Avenue', 'Springfield', 'NJ', '07081          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (578, 'Cefalu, George', '19 Winchester St #207', 'Milwaukee', 'WI', '53212          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (579, 'Hines, Enoch', '2416 Westgate Dr', 'Dallas', 'TX', '75201          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (580, 'Swartz, Doug', '405 Pattoon St', 'Irving', 'TX', '75039          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (581, 'Mccann, Chris', 'Po Box 9041', 'Omaha', 'NE', '68127          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (582, 'Wilder, Phil', '210 W. Collins', 'Berkeley', 'CA', '94720          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (583, 'Denny, Scott', '707 East Central', 'Oak Park', 'IL', '60301          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (584, 'Brethauer, Rhonda', '108 Copperfield Road', 'St Louis', 'MO', '63101          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (585, 'Heng, Xiaowei', '800 South Washington Street', 'Clarks Summit', 'PA', '18411          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (586, 'Vulman, George', '340 West Miller Street', 'Westminster', 'CO', '80030          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (587, 'Miller, Roby', '3527 Holmead Pl.', 'Saint Louis', 'MO', '63136          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (588, 'Ibach, Ray', '43155 Wayne Stevens Rd', 'Pompton Plains', 'NJ', '07444          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (589, 'Hubbard, Jill', '128 Pine Hill Avenue', 'Falls Church', 'VA', '22043          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (590, 'Peterson, Arthur', '2682 Southmoore Cove', 'Atlatna', 'GA', '30328          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (591, 'Blow, Raj', '3100 Expressway Apt. 652', 'Livonia', 'MI', '48150          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (592, 'Maltais, Sheri', '3533 Lee Hills Dr.', 'Wyoming', 'MI', '49509          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (593, 'Reeves, Raleigh', '15 Forest Street', 'Eden Prairie', 'M', '55344          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (594, 'Chavan, Rhonda', '518 Commanche Tr.', 'Greensboro', 'NC', '27410          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (595, 'Pineda, Bhargava', '1146-A Easton Ave', 'Olive Branch', 'MS', '38654          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (596, 'Mcmillen, G', 'Po Box 459', 'Kirkland', 'WA', '98033          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (597, 'Hanna, Andrew', '43 Railroad Av', 'Springboro', 'OH', '45066          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (598, 'Foreman, Louis', '138-45 224Th Street', 'Springfield', 'MO', '65804          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (599, 'Bentley, Kieu', '1248 N 119Th St', 'Chica', 'IL', '60606          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (600, 'Ahmed, Uma', '110 Jay Dr.', 'Polk City', 'IA', '50226          ');

INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (601, 'Anderson, Randy', '811 Polo Road', 'Wilmerding', 'PA', '15148          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (602, 'Harrison, Will', '100 Half Day Rd.', 'East Brunswik', 'NJ', '08816          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (603, 'Lind, Bryo', '219 Grenadier Drive', 'Safety Harbor', 'FL', '34695          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (604, 'Guzman, Robert', '194 Crofton Drive', 'Evans', 'GA', '30809          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (605, 'Bathwater, Venkatesh', '605 Suwannee St.', 'Burlingame', 'CA', '94010          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (606, 'Hester, Robert', '1 Constitution Way', 'Baltimore', 'MD', '21244          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (607, 'Gross, Ranji', '26 Mist Hill Drive', 'Madiso', 'SD', '57042          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (608, 'Mukhopadhyay, Kondal rao', '43 Huntington St', 'Herndo', 'VA', '20170          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (609, 'Ranieri, Rich', '118 Huntington Street', 'Housto', 'TX', '77096          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (610, 'Young, James', '6368 Andrews Dr W', 'Buffalo', 'NY', '14203          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (611, 'Coleman, Carl', '30 S. Wacker Dr', 'Dallas', 'TX', '75248          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (612, 'Avula, Glen', '650 South Front St.', 'Matthews', 'NC', '28104          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (613, 'Chen, Mary', '22 Pleasant Street', 'Baltimore', 'MD', '21214          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (614, 'Hinkley, Martha', '2111 E. 37Th St. N.', 'Woodland Hills', 'CA', '91367          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (615, 'Matte, Kris', '1225 Nw Cooke Ave', 'Austi', 'TX', '78148          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (616, 'Galvis, Mike', '4015 Buckingham Road', 'Alexandria', 'VA', '22311          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (617, 'Dennis, Larry', '900 Mickley Rd', 'Lafayette', 'LA', '70506          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (618, 'Murray, Teresa', '1200 Corporate Systems Center', 'St. Louis', 'MO', '63103          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (619, 'Prakash, Richie', '26 Corporate Hill Dr.', 'Carmichael', 'CA', '95608          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (620, 'Buntin, Ravikumar', '5087 Sheridan Dr.', 'Grand Forks', 'ND', '58201          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (621, 'Rehm, Robert', '1900 E. Oakland St.', 'Cedar Falls', 'IA', '50613          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (622, 'Sherman, Steve', '1800 Longcreek Dr.', 'Berwy', 'IL', '60402          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (623, 'Bryant, Shilpa', '21 Meadow Rd.', 'Auburn Hills', 'MI', '48326          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (624, 'Miranda, Bob', '154 Apt # H', 'Carmel', 'I', '46032          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (625, 'Giragani, Michelle', '2335 Saint Albans Place', 'North Wales', 'PA', '19454          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (626, 'Aronov, Mark', '1000 Cherry Lane', 'Mesa', 'PA', '85310          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (627, 'Anto, Joh', '3500 Savannah Park Ln.', 'Alpharetta', 'GA', '30022          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (628, 'Mavraedis, Charles', '1-205 Lamoine Village', 'Cypress', 'TX', '77429          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (629, 'Tankkar, Boris', '1049 Creek Hollow Lane', 'Albany', 'NY', '12203          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (630, 'Blick, Mark', '1335 Bradyville Pike Apt F206', 'Hopkins', 'M', '55343          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (631, 'Mansir, Theresa', '312 Bishop Rd', 'Greenvile', 'SC', '29615          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (632, 'Yang, Daniel', '343 Peach Rd', 'Queens', 'NY', '11362          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (633, 'Phillips, Louis', '90-19 211Th Street', 'Salisbury', 'MD', '21802          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (634, 'Fannin, P.', '5000 Ellin Rd', 'Mitchellville', 'MD', '20721          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (635, 'Kondratieff, Bill', 'P.O.Box 245', 'Omaha', 'NE', '68103-0777     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (636, 'May, Joan', 'Po Box 645910', 'Starkville', 'MS', '39759          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (637, 'Wainscott, Brent', '1129 Treeside L', 'Mahwah', 'NJ', '07430          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (638, 'Akkiraju, Mike', '3811 N. Bell', 'Hazlet', 'NJ', '07730          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (639, 'Davis, Frank', '2222 Welborn St.', 'Milwaukee', 'WI', '53202          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (640, 'Zaslavskaya, Alok', '2850 24Th Avenue', 'Hacienda Heights', 'CA', '91745          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (641, 'Burgess, Jonatha', '5909 Birchbrook', 'Grand Prairie', 'TX', '75050          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (642, 'Hall, Wayne', '6 Reservoir Drive', 'Columbia', 'T', '38401          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (643, 'Lee, Cindy', '1000 Middle St', 'Flushing', 'NY', '11354          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (644, 'Grimm, jr., Ramanatha', '20 Bernard Road', 'Barringto', 'IL', '60010          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (645, 'Cable, Clay', '1463 Timber Ridge Court', 'Gilbert', 'AZ', '85233          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (646, 'Alderman, James', '6405 N Mokane Ct', 'Columbia', 'MD', '21046          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (647, 'Ivy, Erika', '10433 Sunnybrook Circle', 'Baltimore', 'MD', '21207          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (648, 'Kota, Connie', '400 Sir Walter Drive', 'Willingboro', 'NJ', '08046          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (649, 'Deb, Pio', '3855 Blair Mill Rd', 'Mentor', 'OH', '44060          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (650, 'Salazar, Joel', '1601 1St Ave.', 'El Segundo', 'CA', '90245-3803     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (651, 'Lynn, Nelso', '1945 Lindenwood', 'Brookly', 'NY', '11219          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (652, 'Dunn, Ole', '317 Main Street - Info Sys', 'Birmingham', 'AL', '35288          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (653, 'Meadows, Joy', '1429 Senate Street', 'Sacramento', 'CA', '95818          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (654, 'Milliano, Chuan hwa', '2150 Wenlok Trail', 'Chica', 'IL', '60615          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (655, 'Kamble, Keith', '27473 Audrey', 'Carrollto', 'TX', '75006          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (656, 'Lee, Valerie', '1381 Anderson Avenue', 'Sacramento', 'CA', '95814          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (657, 'Jachimski, Myro', '8000 Utopia', 'Glendale', 'AZ', '85302          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (658, 'Zavrotny, Lisa', '4905 Muirwood Dr', 'Glen Alle', 'VA', '23030          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (659, 'Lee, Jeff', '32 Gatehouse Lane', 'Roseville', 'CA', '95829          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (660, 'Weckbecker, Asoka', '4556 Shadowridge Dr', 'Cincinnati', 'OH', '45238          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (661, 'Ritzcovan, Toocee', '2828 Tudor Court', 'West Allis', 'WI', '53227          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (662, 'Chogyoji, Rahul', '2100 Nursery Rd Apt E1', 'Whitehall', 'PA', '18052          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (663, 'Vengala, Kim', '110 Kope Ave', 'Oklahoma City', 'OK', '73112          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (664, 'Turnquist, Sharo', '1222 N. Fieldcrest St.', 'Stephenville', 'TX', '76401          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (665, 'Rodriguez, Earlene', '537 Mansfield Village', 'Jackso', 'MS', '39217          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (666, 'Wu, Jeffrey', '4800 Regent Blvd', 'Como', 'TX', '75431          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (667, 'Amoroso, Hazel-an', '5114 Walnut Haven L', 'Tallahassee', 'FL', '32362          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (668, 'Keeble, Joh', '71 Hanover Rd', 'Louisville', 'KY', '43215          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (669, 'Bozonelos, Pulkit', '3330 N. Causeway Blvd.', 'Las Vegas', 'NV', '89117          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (670, 'Cadle, Michael', '572 Brook Street', 'Van Wert', 'OH', '45891          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (671, 'Patel, Ramesh', '194 Wood Ave, South', 'San Die', 'CA', '92126          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (672, 'Slivkoff, Scott', 'P.O. Box 524', 'Summerville', 'SC', '29483          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (673, 'Krish, Munish', '451 N. Lake Ave.', 'Cedar Rapids', 'IA', '52404          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (674, 'Arumugam, Hemant', '4075, Pineset Drive', 'Dallas', 'TX', '75132          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (675, 'Franklin, Cesar', '5260 Winchester Road', 'Schaumburg', 'IL', '60173          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (676, 'Nguyen, Ram', '1006 Gardens Place', 'Decatur', 'GA', '30030          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (677, 'Carroll, Sam', '9379 N Street', 'Long Beach', 'CA', '90806          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (678, 'Shaw, Warre', '1741 E. Robin Lane', 'Washingto', 'DC', '20002          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (679, 'Powell, Tony', '128 Westridge Dr', 'Latham', 'NY', '12110          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (680, 'Warner, Bala', 'Po Box 335', 'West Hartford', 'CT', '06119          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (681, 'Vera, Anbusekara', '526 Hunterdale Road', 'Columbus', 'OH', '43231          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (682, 'Oneil, Ri', '7961 Inwood L', 'Olympia', 'WA', '98504-3123     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (683, 'Condron, Michael', '866 Butternut Dr.', 'Salinas', 'CA', '93901          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (684, 'Yu, Hemant', '19621 Portsmouth Drive', 'Lanham', 'MD', '20706          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (685, 'Dutton, Philip', '225 Summit Avenue', 'Dacula', 'GA', '30019          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (686, 'Kumar, Manoj', '756 Crocus Lane', 'Charlotte', 'NC', '28269          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (687, 'Wolff, Ke', '820 Club Chase Ct.', 'Ediso', 'NJ', '08837          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (688, 'Collier, Da', '7212 Dalewood Dr.', 'Duluth', 'GA', '30097          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (689, 'Jerome, Beverly', '3206 Greenhollow Dr', 'Metuche', 'NJ', '08840          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (690, 'Leonnig, Timothy', '1802 Bel Air Dr', 'Columbus', 'OH', '43229          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (691, 'Mceachen, Art', '4204 Greencastle Ct.  102', 'Spring', 'TX', '77373          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (692, 'Czarnik, Mark', '480 Valley Rd., A15', 'Mankato', 'M', '56001          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (694, 'Lowe, Doug', '3251 W. Ellery', 'Fresno', 'CA', '93711          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (696, 'Smith, Lawrence', '2883 Sicamore Street', 'Fresno', 'CA', '93711          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (697, 'Wilson, Wilso', '4288 Maple', 'Fresno', 'CA', '93711          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (698, 'Blake, Joh', '388 Sicamore', 'Fresno', 'CA', '93704          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (699, 'Wilkins, Adria', '488 Maple', 'Fresno', 'CA', '92707          ');

-- enable foreign key constraints
	set foreign_key_checks=1;
	set sql_safe_updates=1;
END$$
DELIMITER ;
