DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `usp_testingResetCustomer1Data`()
BEGIN

-- disable foreign key constraints first
	set foreign_key_checks=0;
    set sql_safe_updates=0;
	delete from Customers;
    
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (1, 'Molunguri, A', '1108 Johanna Bay Drive', 'Birmingham', 'AL', '35216-6909     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (2, 'Muhinyi, Mauda', '1420 North Charles Street', 'New York', 'NY', '10044          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (3, 'Antony, Abdul', '1109 Powderhorn Drive', 'Fayetteville', 'NC', '28314          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (4, 'Smith, Ahmad', '2509 South Crescent', 'Savanna', 'IL', '61074          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (5, 'Chen, Rabi', '2273 N. Essex L', 'Murfreesboro', 'T', '37130          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (6, 'Nuckols, Heather', '150 Hayes St', 'Elgi', 'IL', '60120          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (7, 'Lutonsky, Christopher', '293 Old Holcomb Bridge Way', 'Woodland Hills', 'CA', '91365          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (8, 'Reddy, Aj', 'P.O. Box 9802', 'Plano', 'TX', '75025-0587     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (9, 'Rascano, Darrell', '16 Remington Dr. E', 'Rancho Cordova', 'CA', '95760          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (10, 'Johnson, Ajith', '2200 Old Germantown Road', 'McGrer', 'CA', '55555          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (11, 'Patwardhan, Joh', '2512 Shades Crest Rd', 'Bethel Park', 'PA', '15102          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (12, 'Swenson, Vi', '102 Forest Drive', 'Albany', 'OR', '97321          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (13, 'Nichols, Nadine', '7403 Twin Brooks Blvd', 'Rogers', 'AR', '72756          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (14, 'Guthrie, Rawle', '3011 Belden Street', 'Phoenix', 'AZ', '85023          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (15, 'Nguyen, Alliso', '4100 Coca-Cola Plaza', 'Memphis', 'T', '38118          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (16, 'Kandregula, Howard', '534 Radar Road', 'Oklahoma City', 'OK', '73132          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (17, 'Yudkevich, Ed', '1701 E. 12Th Street', 'Olathe', 'KS', '66062          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (18, 'Jii, ', '1678 Plateau Dr', 'Dracut', 'MA', '01826          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (19, 'Schreiber, Nick', '1815 E. Newberry St', 'Lawrenceville', 'NJ', '08648          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (20, 'Chamberland, Sarah', '1942 S. Gaydon Avenue', 'Doraville', 'CA', '30340          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (21, 'ldman, Do', 'Po Box 645910', 'Newark', 'NJ', '07103          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (22, 'Rivas, Brent', '18242 S. 65Th Ave.', 'Duncanville', 'TX', '75137          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (23, 'Newlin, Sherma', '2400 Bel Air, Apt.345', 'Broomfield', 'CO', '80020          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (24, 'Chavez, Grery', '6472 Mll Ct', 'Frederick', 'MD', '21703          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (25, 'De la fuente, Cathy', '2213 Abbotsford Dr', 'Dalto', 'GA', '30720          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (26, 'Lin, Terri', '280 Briarcliff Rd', 'Springfield', 'IL', '62702          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (27, 'Mercado, Vincent', '637 Fulton Rd,  71', 'Boise', 'ID', '83704          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (28, 'Thornton, Sreedhar', '2542 N  Mozart', 'Brookly', 'NY', '11229          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (29, 'Johnson, Pradeep', 'P.O. Box 81171', 'Ws', 'RI', '02890          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (30, 'Leach, Venkat', '12033 Foundation Place', 'Rowland Hts', 'CA', '91748          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (31, 'Muru, Eric', '300 Sixth Avenue', 'Henderso', 'NV', '89052          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (32, 'Slabicki, Liuy', '1979 Marcus Ave.', 'Westwood', 'NJ', '07675          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (33, 'Lair, Andrew', '28 Marblestone Lane', 'San Francisco', 'CA', '94122          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (34, 'Johnson, Waylo', '440 Richmond Park East', 'Hamde', 'CT', '06517-2703     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (35, 'Morgan, Robert', '48289 Fremont Blvd', 'Carrollto', 'TX', '75006          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (36, 'Annamanaidu, Christia', '213 N. College Dr.', 'Omaha', 'NE', '68127          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (38, 'Beier, Aneta', '8204 Anderson Road', 'Temple', 'TX', '76504          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (39, 'Fernandes, Philip', '136 Gales Drive', 'Richmond Hts', 'OH', '44143          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (40, 'Roby, Chris', '182 Greylock Parkway', 'Sacto', 'CA', '95814          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (41, 'Kumari, pinath', '35 Manor Dr. Apt# 5-O', 'Queens Village', 'NY', '11428          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (42, 'Pardo, Harriet', '141 Summit Street', 'Waldorf', 'M', '56091          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (43, 'Haldorai, Brent', '1427 Valley', 'Huntsville', 'AL', '35806          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (44, 'Miller, Jeremy', '625 Woodsmoke', 'Plano', 'TX', '75023          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (45, 'Jain, Phyllis', '75 Lexington Court', 'Austi', 'M', '55912          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (46, 'Nataraj, Randy', '1409 Coliseum Blvd', 'Wesley Chapel', 'FL', '33544          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (47, 'Sellers, Timothy', '13700 Sutton Park Dr N -- #322', 'Dallas', 'TX', '75287          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (48, 'Allen, Deanna', '766 Willow Ridge Dr', 'Demotte', 'I', '46310          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (49, 'Huebner, Walter', '100 Peachtree St.', 'Jacksonville', 'FL', '32217          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (50, 'Hutcheson, Larry', '2902 Cannons Lane', 'Coffeyville', 'KS', '67337          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (51, 'Green, Eduardo', '1240 E. Diehl Road', 'Columbia', 'SC', '29209          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (52, 'Azure, Mike', '304 Combs', 'Mendo', 'NY', '14606          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (53, 'Dardac, Donald', '4232 Judah', 'Irving', 'TX', '75038          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (54, 'Deguzman, Jose', '4168 Woodland Road', 'Brookly', 'NY', '11226          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (55, 'Wolff, Jonatha', '7921 Lamar', 'Ann Arbor', 'MI', '48108          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (56, 'Johnson, Mark', '1538 Harmon Cove Tower', 'Greenville', 'NC', '27889          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (57, 'Leach, Ala', '147 Bear Creek Pike', 'Dallas', 'TX', '75218-3995     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (58, 'Marlatt, Robert', 'P.P. Box 139', 'Yorktown Heights', 'NY', '10598          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (59, 'Perlman, Lk', '505 Ellis Blvd', 'Philadelphia', 'PA', '19122-6083     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (60, 'Brown, Scott', '919, 137Th Avenue Ne', 'Kansas City', 'KS', '66102          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (61, 'Stein, George', '95 Carleton St', 'New Milford', 'NJ', '07646          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (62, 'Petway, Robert', '303 3Rd Ave Se', 'Jacksonville', 'FL', '32224          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (63, 'Robinson, Timothy', '3075 Highland Parkway', 'Westland', 'MI', '48185          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (64, 'odwin, Mark', '6639 Capitol Blvd', 'Montmery', 'AL', '36130          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (65, 'Mallipeddi, Rick', '1876 Woodhollow Dr', 'Milpitas', 'CA', '95035          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (66, 'Buford, Bry', '540 W North West Highway', 'New York', 'NY', '10005          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (67, 'Fritz, Mark', '16 Erie', 'Hosuto', 'TX', '77077          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (68, 'Hamilton, Kare', '18 Marvin Dr., Apt#B-5', 'Cincinnati', 'OH', '45263          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (69, 'Ybarra, George', '6 Oneill Ct', 'Detroit', 'MI', '48206-1775     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (70, 'Varghese, Joanne', '7178 Talhelm Road', 'Fort Wayne', 'I', '46805-1499     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (71, 'Santos, Anita', '1640 Barrington Lane', 'Barringto', 'IL', '60448          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (72, 'Kieffer, Jing peng', '1492 Highland Lakes Trail', 'Ringld', 'GA', '30736          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (73, 'Seaver, Glenda', '23 Holohan Drive', 'Mountlake Terrace', 'WA', '98043          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (74, 'Knox, Lakshma', '9074 Estes St', 'Austi', 'TX', '78759          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (75, 'Wigton, Alex', '5033 Monte Bay Dr', 'Brookly', 'NY', '11245          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (76, 'Ryan, Jagriti', '115 Audubon Cove', 'Kingsport', 'T', '37663          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (77, 'Latheef, Andrea c.', '17 Potter Road', 'Jacksonville', 'FL', '32256          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (78, 'Konow, Andrew', '25677 Wistereia Ct', 'Greenville', 'SC', '29607          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (79, 'Chang, Simo', '8317 Cabin Creek Drive', 'Oshkosh', 'WI', '54901          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (80, 'Garcia, Chong', '28000 Dequindre', 'Fairfax', 'VA', '22033          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (81, 'Schlusselberg, Brando', '303 South Second St.', 'Collinsville', 'IL', '62234-2973     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (82, 'Boan, Dinesh', '11582 Rusk Cove', 'Charlotte', 'NC', '28270          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (83, 'Dalton, Tai-ye', '115 Tower Drive', 'Round Rock', 'TX', '78681          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (84, 'Wieneke, Frank', '2111 Bancroft Way', 'Birmingham', 'AL', '35226          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (85, 'Trujillo, Thell', '1204 Keller Lane', 'Fairfield', 'IA', '52556          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (86, 'Ritz, Joe', '7404 Lomo Alto', 'Plano', 'TX', '75024          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (87, 'Chen, Becky', '2605 Hawthorne Ave', 'Southgate', 'MI', '48195          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (88, 'Monse, Charles', '5933 6Th Street', 'Somersert', 'NJ', '08873          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (89, 'Boswell, Joseph', '3131 E. Holcombe Blvd', 'Shelto', 'CT', '06484          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (90, 'Johnson, Stewart', '410 Victory Garden Dr. Apt. 36', 'San Die', 'CA', '92111          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (91, 'Cummings, Usha', '12033 Foundation Place', 'Greenville', 'TX', '75401          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (92, 'Aguimba, Edward', '444 Propsect St', 'Streamwood', 'IL', '60107          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (93, 'Lacey, Kimberly', '3450 W. Country Club Dr', 'Macomb', 'MI', '48044          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (94, 'Vega, Bharat', '3003 N. First St. Ste309', 'Little Elm', 'TX', '75068          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (95, 'Cheboli, Walter', '4260 Nw 32 Street', 'Mankato', 'M', '56002          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (96, 'Bawa, Jerry', '315 Newport Lane', 'Rockville', 'MD', '20850          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (97, 'Yciano, Nicolette', '1295 State Street', 'Gettysburg', 'PA', '17325          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (98, 'Duvall, Billy', 'Box 123', 'Fremont', 'CA', '94536          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (99, 'Trasente, Lucy', '51783 Se 7Th Street', 'Westerville', 'OH', '43081          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (100, 'Hodgkins, Giridhar', '814 East Ivy Street', 'Nyc', 'NY', '110324         ');

INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (101, 'ldberg, Seth', '4647 Stone Avenue', 'Huntsville', 'TX', '77320          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (102, 'Hernandez, Esta', '4000 So. 35Th', 'Hagerstow', 'MD', '21742          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (103, 'Trent, Janet', '13101 Columbia Pike', 'San Francisco', 'CA', '94122          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (104, 'Wheatley, Sathyanarayana', '2226 Spring Dusk Lane', 'Bloomingdale', 'NJ', '07403          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (105, 'Williams, Eugene', '805D Columbia St.', 'Flushing', 'NY', '11355          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (106, 'Smisko, Steve', '104 Cinnamon Teal Court', 'Warre', 'MI', '48089          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (107, 'Travis, Jeff', '3111 Monument Drive', 'Milwaukee', 'WI', '53218          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (108, 'Broadhurst, Vito', '300 30Th Ave. N. Apt. 4C', 'Fennimore', 'WI', '53809          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (109, 'Chansa, Tom', '123 Sfsdfsdfsdf', 'Sacramento', 'CA', '95820-4617     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (110, 'Sanjay, Ia', '517 So. Main Street', 'Gainesville', 'FL', '32301          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (111, 'Perkins, Wm', '900 Old Country Rd', 'Grand Prairie', 'TX', '75052          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (112, 'Paramasivan, Nancy', '923 Fuchsia Ave', 'Alamo', 'CA', '94507          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (113, 'Kohli, Carl', '51 Mercedes Way', 'Hollister', 'CA', '95023          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (114, 'Nuytten, Kim', '8908 So 121St', 'Chattanooga', 'T', '37404          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (115, 'Gagne, Joh', '2156 Glencoe Hills Drive.# 6', 'Sumter', 'SC', '29154          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (116, 'Sun, Edgar', '39 Howell Place', 'Parsippany', 'NJ', '07054          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (117, 'Bounds, Kirk', '1818 South 43Rd Street', 'Collinsville', 'IL', '62234          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (118, 'Palanukumarasamy, Dianna', '1521 W Wolfram', 'Columbia', 'SC', '29223          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (119, 'Donahoe, Greg', 'P. O. Box 2600', 'St. Paul', 'M', '55101          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (120, 'Bucella, Alex', '3451 Fairway Commons Dr', 'Colorado Springs', 'CO', '80907          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (121, 'Demith, Bob', '20 Carlsbad Rd.', 'New York', 'NY', '10007          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (122, 'Giraka, Eric', '115 Williams St Se', 'Seatle', 'WA', '98036          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (123, 'Jackson, Bill', '25-3 Latham Villiage Lane', 'Parma', 'OH', '44134          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (124, 'Bruch, Camero', '10925 South Bryant', 'Addiso', 'TX', '75001          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (125, 'Chism, Leslie', '123 Main St', 'Roy', 'UT', '84067          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (126, 'Beemer, Steve', '1234 Main St', 'Watertow', 'CT', '06795          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (127, 'Garcia, Dhananjay', '9211 Garland', 'Columbus', 'OH', '43216          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (128, 'Susai, Jo', '42524 Parkhurst Rd.', 'Mansfield', 'MA', '02048          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (129, 'Pot, Jonatha', '14647 S. Peppermill Ct.', 'Madiso', 'NJ', '07940          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (130, 'fedor, sr., Christy', 'Beltline Road', 'Austi', 'TX', '78745          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (131, 'Wazny, Tina', '1025 Cadillac Way', 'Birmingham', 'AL', '35242          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (132, 'Daniel, Jody', '1 Enterprise Dr', 'Phoenix', 'AZ', '85032          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (133, 'Binner, Ellis', '6855 Woodland Ave', 'New Milford', 'CT', '06776          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (134, 'Rasmussen, Da', '1066 Hidden Lake Dr', 'Meride', 'CT', '06450          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (135, 'Robinson, Clemente', 'Sis, 550 Banway Building', 'Downers Grove', 'IL', '60515          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (136, 'Bennett, nza', '2707 Villagerive', 'Baltimore', 'MD', '21229          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (137, 'Lavallee, Lawrence', '2634 Timberbrooke Way', 'San Jua', 'PR', '00936          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (138, 'Harris, Peter', '3001 S. Congress', 'Indianapolis', 'I', '46237          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (139, 'Shukla, An', '20743 Chappell Knoll Dr', 'Appleto', 'WI', '54913          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (140, 'Look, Christina', '2014 Widener Place', 'Amarillo', 'TX', '79102          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (141, 'Seale, Brent', '1421 Champion Drive Suite 101', 'Carlstadt', 'NJ', '07072          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (142, 'Tuttle, Richard', '2829 Bennett Ave', 'East Northport', 'NY', '11731          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (143, 'Hardin, Bruce', '669 Woodspring Drive', 'Arlington Hts', 'IL', '60005          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (144, 'Erpenbach, Lee', '901 Mission Street', 'Grants Pass', 'OR', '97526          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (145, 'Tonner, Zheng', '57 N Plaza Blvd', 'Atlanta', 'GA', '30339-4024     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (146, 'Wilbon, Albert', '6035 Parkland', 'Kansas City', 'MO', '64141          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (147, 'Horner, Henry', '1206 Applegate Prkwy', 'Indianapolis', 'I', '46250          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (148, 'Buckley, Robert', '26280 Bonnie', 'San Gabriel', 'CA', '91776-3916     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (149, 'Benedicto, Robert', '4140 Alpha Road', 'Columbia', 'SC', '29223          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (150, 'Corbett, Jayagangadhara', '13050 Dahlia Circle,  122', 'Sherwood', 'AK', '72120          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (151, 'Bommana, Ilya', '1310 Brook St #2A', 'San Rafael', 'CA', '94903          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (152, 'Rimes, George', '977 N. Rustic Circle', 'Copperas Cove', 'TX', '76522          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (153, 'Aneshansley, Baskara', '6720 Upper York Road', 'Ramona', 'CA', '92065          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (154, 'Battu, Jeffrey', '458 Mehaffey Drive', 'Succasunna', 'NJ', '07876          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (155, 'Brock, David', '651 Brookfield Pkwy', 'Farmington Hills', 'MI', '48864          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (156, 'Mogesa, Mohamed', '9939, Fredericksburg Rd, Apt', 'Overland Park', 'KS', '66212          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (157, 'Abeyatunge, Derek', '1414 S. Dairy Ashford', 'North Chili', 'NY', '14514          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (158, 'Shaffer, Jack', '1371 Longford Circle', 'Tampa', 'FL', '33634          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (159, 'Berger, Anil', '3968 Holly Dr.', 'Ediso', 'NJ', '08830          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (160, 'Desormeaux, Ram', '1219 Redcliffe Road', 'Sunnyvale', 'CA', '94087          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (161, 'Smith, Mark', '89-41 210Th Pl', 'Okc', 'OK', '73117          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (162, 'Meseguer, Ala', '311 Sinclair Frontage Rd', 'Housto', 'TX', '77047          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (163, 'Alexander, Skip', '15 Gettysburg Square  187', 'West Hartford', 'CT', '06107          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (164, 'Louie, Guy', '1601 Schlumberger Dr', 'Baltimore', 'MD', '21228          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (165, 'Ambati, Greg', '1605 Candletree Dr. Suite 114', 'Landover', 'MD', '20785          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (166, 'Perkins, Kosalai', '1350 Davenport Mill Rd', 'Orlando', 'FL', '55555          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (167, 'Maksymczak, Timothy', '8425 Dolfor Cove', 'St Louis', 'MO', '63138          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (168, 'Billingsley, Carlos', '123 Sw 32Nd St', 'San Juan Capistrano', 'CA', '92675          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (169, 'Henry, Benjami', '9203 Ivanhoe Road', 'Phoenix', 'AZ', '85016          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (170, 'Srinivas, Nicholas', '4792, Apt A, Weybridge Road', 'Hendersonville', 'T', '37075          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (171, 'Ashley, Karla', '108 Randolph Avenue', 'Sunrise', 'FL', '33351          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (172, 'Arutla, Jerry l.', '209 Ne 6Th', 'Ontario', 'CA', '91762          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (173, 'Kiss, Michelle', '201 Rockview Drive', 'Baton Rouge', 'LA', '70898          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (174, 'Wipfli, Jenny', '5502 Elk Hollow Ct', 'Mcfarland', 'WI', '53558          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (175, 'Perkins, Randy', '500 Franklin Trpk', 'Bellevue', 'NE', '68005          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (176, 'Lee, Bruce', '2388 Springdale Rd., Sw', 'Powder Springs', 'GA', '30127          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (177, 'Briggs, Greiner', '10011 Strathfield L', 'Vestavia', 'AL', '35216          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (178, 'Dinan, Kelly', '875 Taylor Road', 'Bayside', 'NY', '11361          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (179, 'Molfese, Alexander', '34 Knox Lane', 'Los Angeles', 'CA', '90068          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (180, 'Johnson, Neelam', '37220, Eisen Hoover Ct', 'Addiso', 'TX', '75001          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (181, 'Maberry, Paul', '1525 Buchanan St., Nw', 'Apex', 'NC', '27502          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (182, 'Wolfe, Randy', '3799 Route 46 East', 'Columbus', 'GA', '31904          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (183, 'Hoffman, Kevi', '5375 Mariners Cove Drive', 'Everett', 'MA', '02149          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (184, 'Rogers, Pete', '906 233Rd Pl Ne', 'Erie', 'PA', '16505          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (185, 'Arzuza, Alioune', '113 Railroad Ave.', 'Dallas', 'TX', '75252          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (186, 'Williams, Greg', '5400 Gingercovedr', 'Spring Valley', 'NY', '10977          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (187, 'Holston, B', '1157 Hampton Way Ne', 'Rancho Cordova', 'CA', '95670          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (188, 'Sundaram, Kelly', '4905 Dunckel', 'Ore', 'WA', '98121          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (189, 'Karri, Lisa', '22 Winding Way', 'Phoenix', 'AZ', '85016          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (190, 'Yarbro, Joh', '2320 Mountain Oaks Lane', 'Dayto', 'OH', '45415          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (191, 'Shah, Dave', '1251 42Nd St. 4Th Floor', 'Fayetteville', 'AR', '72701          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (192, 'Piper, Ala', '341 Carlton Road', 'Blue Bell', 'PA', '19422          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (193, 'Paramasivam, Greg', '1013 N. Franklin St', 'Burnsville', 'M', '55306          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (194, 'Wallace, Stephe', '63 N. Victor Ave.', 'Tallahassee', 'FL', '32399-0450     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (195, 'Zimmer, Jia', '4633 Tarsall Ct', 'Cinnaminso', 'NJ', '08077-2308     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (196, 'Barksdale, Kare', '214 Main St  249', 'Housto', 'TX', '77021          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (197, 'Bilodeau, Kenendy', 'One Sbc Center', 'Ediso', 'NJ', '08817          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (198, 'Gilliam, James', '1910 Patricia', 'Matteso', 'IL', '60443          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (199, 'Abueg, Do', '901 N. Lake Destiny', 'Montvale', 'NJ', '07645          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (200, 'Taliaferro, Eric', '2101 E Coliseum Blvd', 'Westmont', 'IL', '60559          ');

-- enable foreign key constraints
	set foreign_key_checks=1;
	set sql_safe_updates=1;
END$$
DELIMITER ;
