DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `usp_testingResetCusomer2Data`()
BEGIN

-- disable foreign key constraints first
	set foreign_key_checks=0;
    set sql_safe_updates=0;
    
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (201, 'Hull, Tom', '301 W. Bay St.', 'Natick', 'MA', '01760          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (202, 'Beleford, Njansi', '2136 E Main St', 'Collinsville', 'IL', '62234          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (203, 'Kanapilly, Bill', '443 Eldridge Rd', 'Norcross', 'GA', '30096          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (204, 'Smith, Chris', '14254 W Center Dr', 'Levittow', 'PA', '19055          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (205, 'Blasy, Howard', '10 Blue Ravine', 'Plano', 'TX', '75074          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (206, 'Szara, Elle', '714 P Street', 'Jacksonville', 'FL', '32202          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (207, 'Montenegro, M.e', '722 N. Broadway', 'Oakland', 'CA', '94612          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (208, 'Cullity, Yolanda', '312 S. Combs', 'Norwood', 'MA', '02062          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (209, 'Gamba, Jeffrey', '726 Brender Lane', 'Hermitage', 'T', '37076          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (210, 'Salazar, Sidney', '5845 S. 2325 W.', 'St Louis', 'MO', '63129          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (211, 'Wheeler, Caroline', '185 Whiting Lane', 'Madiso', 'WI', '53704          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (212, 'Beck, Mike', '5316 Easthorpe Drive', 'Nutley', 'NJ', '07109          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (213, 'Browning, Albert', '1  E. Telecom Parkway', 'Duluth', 'GA', '30097          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (214, 'Uchendu, Jim', '4905 Maffitt Place', 'Ba', 'OK', '74011          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (215, 'Robersone, Sumanta', '206 Mc Lain Rd.', 'Atlanta', 'GA', '30313          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (216, 'Brown, Bob', '100 Schooner Way', 'Bedford', 'OH', '44146          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (217, 'Boos, James', '7647 Ellington Place', 'Holmdel', 'NY', '07733          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (218, 'Cooke, Arpa', '9834 Morgan Meadows Cove', 'Brookly', 'NY', '11236          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (219, 'Morisset, Chou', '14120 Twisting Lane', 'West Palm', 'FL', '32106          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (220, 'Carroll, Steve', '560 Main Street   416', 'Rogers', 'AR', '72756          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (221, 'Lawrence, Nunzio', '87 Cannon Ridge Drive', 'Woodside', 'NY', '11377          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (222, 'Suyam, Steve', '1486 Neil Ave', 'Gilbert', 'AZ', '85040          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (223, 'Romano, B.j.', '47715 Freedom Valley', 'Bosto', 'MA', '02116          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (224, 'Daniels, Joh', '1417 Deer Spring Court', 'Fairfax', 'VA', '22031          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (225, 'Milke, Paul', 'Po Box 846', 'Raleigh', 'NC', '27604          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (226, 'Rocca, Cary', '8619 W. Summerdale  1', 'Oakland', 'CA', '94612          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (227, 'Hassan, Robert', '1221 Idaho St', 'Altoona', 'PA', '16602          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (228, 'Sadras, Terry', '43-70, Kissena Blvd.,', 'Belleville', 'IL', '62223          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (229, 'Rivera, Pramod', '2203 , od Shepherd Way', 'Solo', 'OH', '44139          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (230, 'Walters, Tim', '9315 Avenue A', 'Akro', 'OH', '44313          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (231, 'Lee, Andra', '8831 Park Central Drive', 'Beaco', 'NY', '12508          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (232, 'Murphy, Dea', '105 White Lane', 'Phoenix', 'AZ', '85032          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (233, 'Kittendorf, Joe', '6430 95th Avenue', 'Naperville', 'IL', '60623          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (234, 'Liao, Stuart', '4070 Fisher Road', 'Charlotte', 'NC', '28215          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (235, 'Tabor, Michael', '105 Shelley Avenue', 'Beaverto', 'OR', '97007          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (236, 'Burt, Myro', '3201 Clayton Road', 'Huntingto', 'AR', '72940          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (237, 'Erikson, David', '805-D Columbia St', 'Concord', 'NH', '03301          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (238, 'Rathmann, Mark', '4107C Carrollton Ct', 'Rancho Cordova', 'CA', '95670-4502     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (239, 'Anderson, Jeff', '3625 Duval Rd #223', 'Housto', 'TX', '77045          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (240, 'Nguyen, Eddie', '205A E Main St', 'Housto', 'TX', '77013          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (241, 'Diop, Joh', '6318 Towncrest Court', 'South Pasadena', 'CA', '91030          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (242, 'Hemmer, Deepanja', '2020 Oldfields Circle S Dr', 'Dallas', 'TX', '75208          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (243, 'Gajjela, Jim', '1001 Avenue Of The Americas', 'Nelsonville', 'OH', '45764          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (244, 'Gigante, Kathy', 'P O Box 25009', 'Poughkeepsie', 'NY', '12601          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (245, 'Walker, Walter', '2415 First Avenue', 'New York', 'NY', '10018          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (246, 'Viswanathan, Howard', '37890 Westwood Cir. Apt 205', 'Hindsboro', 'IL', '61930          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (247, 'Chu, Darre', '9  Campus Dr.', 'Horsham', 'PA', '19044          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (248, 'Zmaczynski, Mike', '3907 78Th Drive E', 'Schaumburg', 'IL', '60195          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (249, 'Bradley, Raj', '1115 Huntington Dr.  B', 'Aliquippa', 'PA', '15001          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (250, 'Drake, Doug', '846 President St', 'Linde', 'NJ', '07036          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (251, 'Peng, Roger', '6201 W Olive Ave', 'Baton Rouge', 'LA', '70815          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (252, 'Balliet, Steve', '1 New York Plaza', 'Santa Ana', 'CA', '92703          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (253, 'Bertone, Robert', '4627 Blanche Road  #168', 'Austi', 'TX', '78759          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (254, 'Harding, Shaw', '3480 W 135Th St', 'Novato', 'CA', '94947          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (255, 'Boyle, Teresa', '225 Mt Vernon Dr', 'Cerritos', 'CA', '90703          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (256, 'Mahodaya, Test', '351 Crossing Blvd', 'Anywhere', 'CA', '90210          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (257, 'Koch, Robert', '222South Riverside Plaza', 'Decatur', 'GA', '30034          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (258, 'Curless, Darald', 'P.O. Box 866642', 'West Hills', 'CA', '91304          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (259, 'Rusoff, David', '3305, Society Drv', 'Lincol', 'NE', '68506-4807     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (260, 'Hester, Maurice', '2576 Sheppard Road', 'Kennewickm', 'WA', '99336m         ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (261, 'Herbert, Richard', '542, Maple Dr', 'Charlotte', 'NC', '28211          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (262, 'Mattson, Debora', '1701 Telfair Chase Way', 'Sacramento', 'CA', '95814          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (263, 'Allen, Joel', '2220 W Mission Ln Apt 1127', 'Hilliard', 'OH', '43026          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (264, 'King, Radhakrishna', '901 S. Central Expressway', 'Charlesto', 'SC', '29407          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (265, 'Szydlow, Raymond', '1624 Brougham Place', 'Columbus', 'GA', '31904          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (266, 'Lumpkin, Christopher', '100 Church Street', 'Columbus', 'GA', '31901          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (267, 'Ostrov, Arnold', 'Box 183', 'Harrisburg', 'PA', '17110          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (268, 'Chinna, Larry', '2300 Southeastern Ave', 'Marietta', 'GA', '30062          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (269, 'Shellabarger, Mark', '34613 Winslow Ter', 'Bannockbur', 'IL', '60015          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (270, 'Duncan, Ted', '1003 N. Delano Ave', 'Westminster', 'CA', '92683          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (271, 'Harke, Richard', '300 Mustang St', 'Hazelwood', 'MO', '63042          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (272, 'Craig, Jj', '1430 Sw 12Th Ave.  1314', 'Stamford', 'CT', '06906          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (273, 'Kuiu, Ram', '229 Strawtown Rd', 'North Bend', 'OH', '45052          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (274, 'Johnson, Scott', '14 Horseshoe Lane', 'Carver', 'MA', '02330          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (275, 'Wicks, David', '34-52 60Th Street', 'Maryland Heights', 'MO', '63043-3961     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (276, 'Schuh, Max', '730 Opening Hill Rd', 'Lauderhill', 'FL', '33313          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (277, 'Dawson, Srividhya', '907, Lake Run Cir', 'Falss Church', 'VA', '22041-2536     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (278, 'Melamud, Tammy', '1345 Avenue Of The Americas', 'Cleveland', 'OH', '44111          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (279, 'Woo, Kevi', '1108 W. Indiana Ave.', 'Elk Grove', 'CA', '95758          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (280, 'White, Barbara', '3400 Richmond Parkway #3423', 'Bristol', 'CT', '06010          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (281, 'Schumer, Richard', 'East Remington Drive', 'Woodstock', 'GA', '30188          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (282, 'Brownstein, Ruth', '6142C S. Kensington Ave.', 'Boise', 'ID', '83278          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (283, 'Demers, Ro', '4Th Floor  F6-F266-04-1', 'Conyers', 'GA', '30013          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (284, 'Vennapusa, Rani', '7895 Surreywood Dr.', 'Dallas', 'TX', '75218          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (285, 'Jefferies, Gloria', 'Matera St', 'San Bruno', 'CA', '94066          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (286, 'Underwood, Al', '3520 Twilight Dr', 'Indianapolis', 'I', '46227          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (287, 'Kk, Darnell', '1121 Tama', 'Middletow', 'RI', '02842          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (288, 'Douglas, Bikash', '2220 Canton St  Loft 301', 'Columbus', 'WI', '53925          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (289, 'Drebenstedt, Thomas', '11 Main Street', 'Florham Park', 'NJ', '07932          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (290, 'Turner, Eric', '1728 S. 15Th', 'Arvada', 'CO', '80002          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (291, 'Volkov, Jim', '12033 Foundation Place', 'Chica', 'IL', '60618          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (292, 'Westemeier, Linda', '722 N Broadway', 'Jonesboro', 'AR', '72401          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (293, 'Disanto, Be', '402 Clover Springs Drive', 'Irvine', 'CA', '92612          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (294, 'Stroede, George', '14115 Fleetwell', 'Washingto', 'DC', '20065          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (295, 'Long, Leo', '16 Saint Mary Drive', 'Scappoose', 'OR', '97056-4484     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (296, 'Parmelee, Robert', '1810 Berry L', 'Commerce', 'TX', '75428          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (297, 'Smith, Deb', '985 Michigan Av', 'Lakewood', 'CO', '80228          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (298, 'Smit, Rekha', 'Computer Science Department', 'Topeka', 'KS', '66612          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (299, 'Hall, An', '114 12Th Ave Nw', 'Tallahassee', 'FL', '32301          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (300, 'Shaw, Ronald', '656 Riverside Dr', 'Tusti', 'CA', '92780          ');

INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (301, 'Gujja, Anthony', '4747 Mclane Parkway', 'Irving', 'TX', '75038          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (302, 'Kundargi, Danial', '57 Nevada Dr.', 'Alpharetta', 'GA', '30004          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (303, 'Andrews, Ashok', '949 Rockybrook Drive', 'Raleigh', 'NC', '27613          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (304, 'Blanchard, Eilee', '11 Harbor Woods Circle', 'Tallahassee', 'FL', '32312          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (305, 'Cao, Kelly', '906 Dryden Ave', 'Atlanta', 'GA', '30303-3404     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (306, 'Bobson, Manohar', '2200 Cardinal Drive', 'Hermosa Beach', 'CA', '90254          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (307, 'Valentin-eggert, Michael', '140, Broadway', 'Indianapolis', 'I', '46221          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (308, 'Pierre, Robert', '155 Grisseltail Rd', 'Park Ridge', 'IL', '60056          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (309, 'Grampsas, Jiying', '1200 Wooded Acres Dr.', 'Ames', 'IA', '50010          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (310, 'Jeffcoat, Nelso', '5244 West 139Th Street', 'Portland', 'TX', '78374          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (311, 'Casoli, Da', '5 Conrad Court', 'Prairie Village', 'KS', '66208          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (312, 'Hidal, Fgsdg', '405 Fayette Pike', 'Austi', 'TX', '78704          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (313, 'Murphy, Coli', '3831 Pinetree Dr.', 'Asheville', 'NC', '28806          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (314, 'nzalles, Maiv', '10610 Morado Circle', 'Jopli', 'MO', '64801          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (315, 'Reinarz, Craig', '1339 Contra Costa Drive', 'Bernville', 'PA', '19506          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (316, 'Appandai, Curtis', '443 Airpark Rd', 'Grand Prairie', 'TX', '75052          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (317, 'Brown, Srikanth', '1155 Warburton Ave', 'Richmond', 'CA', '94806          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (318, 'Avula, Manuel', '2217 North Ave', 'Lake Success', 'NY', '11042          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (319, 'Mcdermott, Clifford', '162 Quail Ru', 'Chica', 'IL', '60643          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (320, 'Bernard, Subramaniya', '125 Raritan Plaza', 'Birmingham', 'AL', '35222          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (321, 'Sridar, Ashok', '5146 Keitts Corner Road', 'Liverpool', 'NY', '13090          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (322, 'Lorusso, Walt', '6509 Rosemeadows Dr', 'Las Cruces', 'NM', '88003          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (323, 'Marshburn, Sridhar reddy', '1530 Broadway Road', 'Brookly', 'NY', '11219          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (324, 'Brown, Connie', '10302 Joan Drive', 'Appleto', 'WI', '54915          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (325, 'Tucker, Bill', '3003 North First Street', 'Milwaukee', 'WI', '53202          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (326, 'Howell, Kim', '4010 Bob Wallace Ave Apt 3', 'Rento', 'WA', '98056          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (327, 'Bostick, Alle', '7205 None Rd.', 'Montmery', 'WV', '25136          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (328, 'Alsaidi, Jim', '712 White Oak', 'Apopka', 'FL', '32712          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (329, 'Delatte, William', '2521 Old Stone Mill Drive', 'Lewisville', 'TX', '75067          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (330, 'Krishnamurthy, William', '1110 Ne 12Th St', 'Cranbury', 'NJ', '08512          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (331, 'Howard, Denise', '1517 Wn Carrier Pkwy. Ste. 150', 'Wincester', 'T', '37398          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (332, 'Galloway, Mariola', 'P.O. Box 250587', 'New York', 'NY', '10025          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (333, 'Loyal, Chang', 'R.R. 1  Box 132', 'Jacksonville', 'FL', '32207-3713     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (334, 'Kaphle, Carlos', '111 Wall St.', 'Housto', 'TX', '77221          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (335, 'Srigiri, Greg', '725 Lake St Ne', 'Wesley Chapel', 'NC', '28173          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (336, 'Mccue, Sreepathi', '914 Dundee Ct', 'Tinlry Park', 'IL', '60477          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (337, 'Morgan, Joh', '28 lden Hill', 'Tampa', 'FL', '33615          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (338, 'Clegg, Viola', '3635 Vista', 'Mansfield', 'MO', '65704          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (339, 'Kanter, Cindy', '17909 Peru Rd # 37', 'Lawrenceville', 'GA', '30043-5151     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (340, 'Sahoo, Satish', '55 Water Street', 'Lansing', 'MI', '48917          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (341, 'D, Elaine', '3604 Partridge Path Apt 1', 'Rancho Cordova', 'CA', '95670          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (342, 'Sase, Claude', '2963 Jones St.', 'Benicia', 'CA', '94510          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (343, 'Chanduri, Walter c', '1331 Jefferson Avenue', 'Delray Beach', 'FL', '33445          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (344, 'Ibarra, Joh', 'Pob 65', 'Warminster', 'PA', '18974          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (345, 'Phillips, Jeff', '223 Sunlit Way', 'Plymouth', 'MI', '48170          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (346, 'Randazzo, Alaine', 'Hall St', 'Blue Mounds', 'WI', '53562          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (347, 'Brown, Toni', '6050 Crawfordville Rd', 'Housto', 'TX', '77042          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (348, 'Samala, Avelino', '117 Beacon Ave', 'Lawrence', 'MI', '49064          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (349, 'Shanmugasundaram, Joh', '6890 Deer Court', 'Glen Elly', 'IL', '60137          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (350, 'Posh, Kevra', 'P.O Box 1452', 'Jonesboro', 'AR', '72401          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (351, 'Cuento, Joh', '5100 Tipperary', 'Little Rock', 'AR', '72022          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (352, 'Cate, Kim', '123 Wild Lilac Court', 'San Mateo', 'CA', '94402-5009     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (353, 'Johnson, Joh', '23 Main Street', 'Lawrenceville', 'GA', '30043          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (354, 'Bhatt, Andregene', '20533 Sw 2 Nd. Street', 'Westerville Dr W', 'OH', '43082          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (355, 'Jackson, Alex', '1234 Main St.', 'Doylestow', 'PA', '18901          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (356, 'Thelagathoti, Brad', '2010 Glass Rd. Ne Apt 210', 'Dallas', 'TX', '75211          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (357, 'Hausner, William', '2512 N.E. 9 Th St', 'Valparaiso', 'I', '46383          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (358, 'Mead, Aquanetta', '2443 Sunset', 'Kenosha', 'WI', '53142          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (359, 'Vera, Craig', '8Th Floor', 'Columbus', 'OH', '43204          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (360, 'Meek, Frank reyes', '4804 Deer Lake Dr E', 'Ankeny', 'IA', '50021          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (361, 'Register, Ala', '4416 Hartdord Dr.', 'Southfield', 'MI', '48075          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (362, 'Taraszewski, Michael', '1000 I Street', 'Ozone Park', 'NY', '11417          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (363, 'Louis, Leanne', '606 Savannah Highway', 'Tallahassee', 'FL', '32304          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (364, 'Lawson, Sriramana', '14160 Red Hill Ave  106', 'Springfield', 'IL', '62704          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (365, 'Johnson, Anne', '4511 Hezekiah Pl', 'Temple', 'TX', '76504          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (366, 'Bannur, Siva', '252 - 85 Leith Road', 'Milwaukee', 'WI', '53202          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (367, 'Foote, Debra', '15769 Hele', 'Buffalo Grove', 'IL', '60089          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (368, 'Mcdonnell, Siddharth', '2616 Beema', 'New Market', 'MD', '21774          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (369, 'Lakshmanaraju, Jeff', '1388 Warner Ave', 'Berkeley', 'CA', '94720          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (370, 'Womack, Gail', '109 North Street', 'Philadelphia', 'PA', '19146-1716     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (371, 'Burger, Michael', '2325 Keaton Ave., Apt. F', 'Matawa', 'NJ', '07747          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (372, 'B, Rodney', '502 N. Jefferson St', 'Itasca', 'IL', '60143          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (373, 'Funai, Margaret', 'P.O.Box 99220', 'Moorestow', 'NJ', '08057          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (374, 'Then, George', '85 Notre Dame Dr', 'Garden Grove', 'CA', '92840          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (375, 'Toocee, Marie', '4500 Baymeadows Rd', 'Concord', 'CA', '94519          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (376, 'Chiru, Nate', '1609 Ranch View Drive', 'Bellmawr', 'NJ', '08031          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (377, 'Tester, Steve', '2232 Ironwood Ridge Ct', 'Lowell', 'MA', '01854          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (378, 'Das, Robert', '2662, Scotalnd Gree', 'Yonkers', 'NY', '10701          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (379, 'Paul, Sam', '3249 S. Oak Park Ave', 'Chica', 'IL', '60642          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (380, 'Counts, James', 'W3903 Krueger Rd', 'New Milford', 'NJ', '07646          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (381, 'Obul, Hari', '241 Main St', 'Temple Terrace', 'FL', '33637          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (382, 'Berry, R', '513 Little Ave.', 'Paw Paw', 'MI', '49079          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (383, 'Viswanathan, Said', '5 Woodhollow Rd', 'New York', 'NY', '10005          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (384, 'Graziano, Bob', '13101 Columbia Pike', 'Matthews', 'NC', '28105          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (385, 'Gira, Dava', '24 Northfield Rd', 'Raymore', 'MO', '64083          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (386, 'Howe, Samuel', '927A E. Center St.', 'Pittsburgh', 'PA', '15239-2324     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (387, 'Cox, Lawrence', '10 Park Plaza', 'Cloverdale', 'CA', '95425-5440     ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (388, 'Wright, Tanya', '415 W lf Rd', 'Lincolnshire', 'IL', '60069          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (389, 'Matthes, Mark', '750 Crown Cove', 'Salinas', 'CA', '93908          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (390, 'Riza, Matthew', '1263 Greenleaf Loop', 'Lake Oswe', 'OR', '97035          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (391, 'Castle, Kenneth', '1536 Chica Blvd', 'Clearwater', 'FL', '33756          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (392, 'Walker, Bob', '2200 S Fort Apache #2029', 'Sunnyvale', 'CA', '94087          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (393, 'Lockhart, Jagloo', '6349 Beechwood Drive', 'Des Moines', 'IA', '50310          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (394, 'Verma, Jose', '1406 17Th Ave', 'N.M.', 'FL', '33181          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (395, 'Burchard, Jay', '17440 N Tatum Blvd', 'Indianapolis', 'I', '46206          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (396, 'Loper, Demetria', '3801 S. Capital Of Texas Hw', 'Hackettstow', 'NJ', '07840          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (397, 'Hollingsworth, Ed', '626 Picher', 'Columbus', 'OH', '43215          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (398, 'Wise, Norm', '1212 N. Lasalle St., #2201', 'Ft Thomas', 'KY', '41075          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (399, 'Lipsig, Seth', '16 Shallowford Rd.', 'Chica', 'IL', '60656          ');
INSERT Customers (CustomerID, Name, Address, City, State, ZipCode) VALUES (400, 'Litterson, Anthony', '901 S. National Ave.', 'Phila.', 'PA', '19105          ');

-- enable foreign key constraints
	set foreign_key_checks=1;
	set sql_safe_updates=1;
END$$
DELIMITER ;
